export {default as trademark} from "./product/trademark"
export {default as attr} from "./product/attr"
export {default as spu} from "./product/spu"
export {default as sku} from "./product/sku"
export {default as menu} from "./permission/menu"
export {default as role} from "./permission/role"
export {default as auth} from "./permission/auth"
export {default as user} from "./permission/auth"